from typing import TypedDict, Annotated # Annotated means to attach arbitary metadata to function and return values
from backend.models.plan import ResearchPlan
from backend.models.research import ResearchFinding
from backend.models.market import MarketFinding
from backend.models.company import CompanyFinding
from backend.models.trend import TrendFinding
from backend.models.critic import CriticResult
from backend.models.validated import ValidatedFinding
from backend.models.aggregated import AggregatedEvidence
from backend.models.analyst import AnalystResult
from backend.models.report import ReportResult

# Add reducer(for critical_results) to preserve old and new ressults at same time(Often used in Langgrraph)
def append_results(
    existing: list[CriticResult],
    new: list[CriticResult]
):
    return existing + new

#Add reducer for validated_findings
def append_validated_findings(
    existing: list[ValidatedFinding],
    new: list[ValidatedFinding],
):
    return existing + new

class ResearchState(TypedDict): # Langgraph uses state to pass the information.
    # USers Original Question
    user_query: str

    # Tasks Generated by the planner
    research_plan: ResearchPlan | None

    # Findings collected by research agents
    research_results: list[ResearchFinding]

    # Findings from the Market Research Agent
    market_results: list[MarketFinding]

    # Findings from the Company Research Agent
    company_results: list[CompanyFinding]

    # Findings from the Trend Research Agent
    trend_results: list[TrendFinding]

    # For Critic Agent
    critic_results: Annotated[
        list[CriticResult],
        append_results
    ]

    # Validated research findings
    validated_findings: Annotated[
        list[ValidatedFinding],
        append_validated_findings
    ]

    # Aggregated validated evidence
    aggregated_evidence: AggregatedEvidence | None

    # Ananlyse to give the report
    analyst_result: AnalystResult | None

    # Report For presentation
    report_result: ReportResult | None

    # Store the rag embeddings
    rag_context: list[str]

    # We will make research_queue to store the values which needs to be re-researched.
    research_queue: list[dict]

    # TO limit the no of researches
    research_attempts: dict[str, int]

    # To validate the reresearch
    findings_to_validate: list[dict]